package com.police.basedomains;

public enum EventType {
    EMERGENCY_ACCEPTED,
    EMERGENCY_COMPLETED,
    EMERGENCY_FAILED,
    VEHICLES_READY,
    VEHICLES_ERROR,
    VEHICLES_BACKWARD_RECOVERY,
    POLICEMEN_READY,
    POLICEMEN_ERROR,
    POLICEMEN_BACKWARD_RECOVERY
}
