//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.23 at 02:12:52 PM CET 
//


package com.police.vehicles.data;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.police package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.police
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetVehicleRequest }
     * 
     */
    public GetVehicleRequest createGetVehicleRequest() {
        return new GetVehicleRequest();
    }

    /**
     * Create an instance of {@link GetVehicleResponse }
     * 
     */
    public GetVehicleResponse createGetVehicleResponse() {
        return new GetVehicleResponse();
    }

    /**
     * Create an instance of {@link Vehicle }
     * 
     */
    public Vehicle createVehicle() {
        return new Vehicle();
    }

    /**
     * Create an instance of {@link GetVehicleListResponse }
     * 
     */
    public GetVehicleListResponse createGetVehicleListResponse() {
        return new GetVehicleListResponse();
    }

    /**
     * Create an instance of {@link GetVehicleListRequest }
     * 
     */
    public GetVehicleListRequest createGetVehicleListRequest() {
        return new GetVehicleListRequest();
    }

}
