//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.23 at 02:12:52 PM CET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.police.org", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.police.vehicles.data;
