version: '2'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  emergencies:
    image: emergencies:latest
    ports:
      - 8083:8083
    depends_on:
      - kafka
    environment:
      POLICE_KAFKA_SERVER: kafka:29092
  
  policemen:
    image: policemen:latest
    depends_on:
      - kafka
    environment:
      POLICE_KAFKA_SERVER: kafka:29092
  
  vehicles:
    image: vehicles:0.0.1-SNAPSHOT
    depends_on:
      - kafka
    environment:
      POLICE_KAFKA_SERVER: kafka:29092
  
  base-domains:
    image: base-domains:latest
    depends_on:
      - kafka
