//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.23 at 02:12:52 PM CET 
//


package com.police.basedomains.vehicles;
public class Vehicle {

    protected String name;
    protected Type type;
    protected int capacity;

    public Vehicle() {
    }

    public Vehicle(String name, Type type, int capacity) {
        this.name = name;
        this.type = type;
        this.capacity = capacity;
    }

    public String getName() {
        return name;
    }
    public void setName(String value) {
        this.name = value;
    }
    public Type getType() {
        return type;
    }
    public void setType(Type value) {
        this.type = value;
    }

    public int getCapacity() {
        return capacity;
    }
    public void setCapacity(int value) {
        this.capacity = value;
    }

}
